add bot 7000104432  onregularinvesting.calculator
fox-one/mixin.fan pull request #22
Opened 2022-02-28 10:15 UTC by imlidian

Simulate the benefits of historical fixed investment and reunderstand past investment decisions.
To improve current investment decisions by revising their past erroneous concepts.

2022-02-28 13:37 UTC, lyricat requested changes

2022-02-28 13:37 UTC, lyricat commented on src/static/bots/7000104432/index.json
> +      "zn": ["定投计算器", "模拟历史定投收益,重新理解过往投资决策", "改善当下决策质量"]
should be "zh", not "zn"

2022-02-28 13:37 UTC, lyricat commented on src/static/bots/7000104432/index.json
> +    "category": "Utilities",
should be "util", FYI: https://github.com/fox-one/mixin.fan/blob/master/src/bots.ts#L66

2022-02-28 13:37 UTC, lyricat commented on src/static/bots/7000104432/index.json
> +      "support_url": "https://github.com/imlidian"
support_url should not under the "developer". Please refer to other bot's config file https://github.com/fox-one/mixin.fan/blob/master/src/static/bots/7000000014/index.json

2022-03-03 05:18 UTC, imlidian commented on src/static/bots/7000104432/index.json
> +      "zn": ["定投计算器", "模拟历史定投收益,重新理解过往投资决策", "改善当下决策质量"]
done

2022-03-03 05:18 UTC, imlidian commented on src/static/bots/7000104432/index.json
> +    "category": "Utilities",
done

2022-03-03 05:18 UTC, imlidian commented on src/static/bots/7000104432/index.json
> +      "support_url": "https://github.com/imlidian"
done thx a lot

2022-03-03 05:22 UTC, merged